USE [master]
GO

/****** Object:  Database [TRANSPARENCIA]    Script Date: 04/02/2016 16:34:46 ******/
CREATE DATABASE [TRANSPARENCIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TRANSPARENCIA', FILENAME = N'D:\RDSDBDATA\DATA\TRANSPARENCIA.mdf' , SIZE = 31808KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TRANSPARENCIA_log', FILENAME = N'D:\RDSDBDATA\DATA\TRANSPARENCIA_log.ldf' , SIZE = 39936KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TRANSPARENCIA] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TRANSPARENCIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TRANSPARENCIA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET ARITHABORT OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TRANSPARENCIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TRANSPARENCIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TRANSPARENCIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TRANSPARENCIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET RECOVERY FULL 
GO

ALTER DATABASE [TRANSPARENCIA] SET  MULTI_USER 
GO

ALTER DATABASE [TRANSPARENCIA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TRANSPARENCIA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TRANSPARENCIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TRANSPARENCIA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TRANSPARENCIA] SET  READ_WRITE 
GO

